// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idyzixetqbzveqtgkaka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkeXppeGV0cWJ6dmVxdGdrYWthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODM1NTAsImV4cCI6MjA2NDM1OTU1MH0.qNvWX0039785Qc0rlzl2XsHisjFRvrkDCeCelq3Rntk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);